version: '3'
services:  # container

   mongodb:  # name of the container (arbitrary)
      image: mongo # program of the instance we create
      container_name: 'mongodb' # container name
      ports:
         - 27017:27017 #port in local machine : post of the mongo (universal)
   tweet_collector:
      build: tweet_collector/
      volumes: 
         - ./tweet_collector/:/app
      depends_on:
         - mongoDB
   postgres:  # next container to run
      container_name: 'postgres'
      image: postgres:14.1
      restart: always
      hostname: postgres
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=dbtweet
   etl:  # run container with this name
      build: etl_job/
      volumes: 
         - ./etl_job/:/app
      depends_on:
         - postgres
         - mongodb
         
         