version: '3'
services:

  mongodb:
    image: mongo
    container_name: 'mongodb'
    ports:
      - 27017:27017
    networks:
      - dock-db-test
    # volumes:
    #   - ./etl/mongo:/data/db
    

  tweet_collector:
    build: tweet_collector/
    container_name: 'tweet_collector'
    volumes:
      - ./tweet_col/:/app
    depends_on:
      - mongodb   
    networks:
      - dock-db-test
  
  postgresdb:
    image: postgres
    container_name: 'postgres'
    ports:
      - 5555:5432
      # Port OUTSIDE Container:Port INSIDE Container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbtweet
    networks:
      - dock-db-test
    # volumes:
    #   - ./etl/psql:/var/lib/postgresql

  etl:
    build: etl_job/
    container_name: 'etl'
    volumes:
      - ./etl_job/:/app
    networks:
      - dock-db-test
    depends_on:
      - postgresdb
      - mongodb
      - tweet_collector
networks:
  dock-db-test:
    external: false
    name: dock-db-test  
    


